import type { Loan, LoanApplication, LoanPayment, LoanPenalty } from "@/types/loan";

export const MOCK_LOANS: Loan[] = [
  {
    id: "loan-1",
    groupId: "g1",
    groupName: "Ejo Heza Circle",
    principal: 100000,
    currency: "RWF",
    interestRate: 5,
    repaymentPeriodDays: 90,
    disbursedAt: "2025-02-01T09:00:00",
    dueDate: "2025-05-02T09:00:00",
    status: "ACTIVE",
    amountPaid: 50000,
    penaltyAccrued: 2500,
    gracePeriodDays: 7,
    totalInstallments: 4,
    paidInstallments: 2,
  },
  {
    id: "loan-2",
    groupId: "g2",
    groupName: "Kigali Hustlers Fund",
    principal: 50000,
    currency: "RWF",
    interestRate: 3,
    repaymentPeriodDays: 60,
    disbursedAt: "2025-01-15T09:00:00",
    dueDate: "2025-03-16T09:00:00",
    status: "OVERDUE",
    amountPaid: 20000,
    penaltyAccrued: 4500,
    gracePeriodDays: 3,
    totalInstallments: 3,
    paidInstallments: 1,
  },
  {
    id: "loan-3",
    groupId: "g1",
    groupName: "Ejo Heza Circle",
    principal: 30000,
    currency: "RWF",
    interestRate: 5,
    repaymentPeriodDays: 30,
    disbursedAt: "2024-11-01T09:00:00",
    dueDate: "2024-12-01T09:00:00",
    status: "PAID",
    amountPaid: 31500,
    penaltyAccrued: 0,
    gracePeriodDays: 7,
    totalInstallments: 2,
    paidInstallments: 2,
  },
];

export const MOCK_PAYMENTS: LoanPayment[] = [
  {
    id: "pay-1",
    loanId: "loan-1",
    groupName: "Ejo Heza Circle",
    amount: 25000,
    currency: "RWF",
    paidAt: "2025-02-28T11:00:00",
    status: "COMPLETED",
    installmentNumber: 1,
  },
  {
    id: "pay-2",
    loanId: "loan-1",
    groupName: "Ejo Heza Circle",
    amount: 25000,
    currency: "RWF",
    paidAt: "2025-03-31T10:30:00",
    status: "COMPLETED",
    installmentNumber: 2,
  },
  {
    id: "pay-3",
    loanId: "loan-2",
    groupName: "Kigali Hustlers Fund",
    amount: 20000,
    currency: "RWF",
    paidAt: "2025-02-14T09:00:00",
    status: "LATE",
    installmentNumber: 1,
    note: "Paid 4 days late",
  },
  {
    id: "pay-4",
    loanId: "loan-3",
    groupName: "Ejo Heza Circle",
    amount: 15000,
    currency: "RWF",
    paidAt: "2024-11-28T09:00:00",
    status: "COMPLETED",
    installmentNumber: 1,
  },
  {
    id: "pay-5",
    loanId: "loan-3",
    groupName: "Ejo Heza Circle",
    amount: 16500,
    currency: "RWF",
    paidAt: "2024-12-01T08:00:00",
    status: "COMPLETED",
    installmentNumber: 2,
    note: "Includes interest",
  },
];


export const MOCK_USERS = [
  { userId: "user-1", userName: "Alice Umutesi", email: "alice@example.com" },
  { userId: "user-2", userName: "Bob Hakizimana", email: "bob@example.com" },
  {
    userId: "user-3",
    userName: "Claire Ingabire",
    email: "claire@example.com",
  },
];


export const MOCK_PENALTIES: LoanPenalty[] = [
  {
    id: "pen-1",
    loanId: "loan-1",
    groupName: "Ejo Heza Circle",
    amount: 2500,
    currency: "RWF",
    reason: "Instalment 2 paid 3 days late",
    accruedAt: "2025-04-03T00:00:00",
    isPaid: false,
  },
  {
    id: "pen-2",
    loanId: "loan-2",
    groupName: "Kigali Hustlers Fund",
    amount: 2000,
    currency: "RWF",
    reason: "Missed instalment — March",
    accruedAt: "2025-03-17T00:00:00",
    isPaid: false,
  },
  {
    id: "pen-3",
    loanId: "loan-2",
    groupName: "Kigali Hustlers Fund",
    amount: 2500,
    currency: "RWF",
    reason: "Continued non-payment — April",
    accruedAt: "2025-04-16T00:00:00",
    isPaid: false,
  },
];

export const MOCK_LOAN_APPLICATIONS: LoanApplication[] = [
  {
    id: "app-1",
    userId: "user-3",
    userName: "Claire Ingabire",
    groupId: "g1",
    groupName: "Ejo Heza Circle",
    principal: 75000,
    currency: "RWF",
    interestRate: 5,
    repaymentPeriodDays: 90,
    purpose: "Business expansion - retail shop",
    appliedAt: "2025-04-20T10:00:00",
    status: "PENDING_APPROVAL",
  },
  {
    id: "app-2",
    userId: "user-1",
    userName: "Alice Umutesi",
    groupId: "g2",
    groupName: "Kigali Hustlers Fund",
    principal: 120000,
    currency: "RWF",
    interestRate: 4,
    repaymentPeriodDays: 120,
    purpose: "Agricultural equipment purchase",
    appliedAt: "2025-04-18T14:30:00",
    status: "PENDING_APPROVAL",
  },
  {
    id: "app-3",
    userId: "user-2",
    userName: "Bob Hakizimana",
    groupId: "g1",
    groupName: "Ejo Heza Circle",
    principal: 25000,
    currency: "RWF",
    interestRate: 5,
    repaymentPeriodDays: 30,
    purpose: "School fees",
    appliedAt: "2025-04-15T09:00:00",
    status: "APPROVED",
    reviewedBy: "Admin John",
    reviewedAt: "2025-04-16T11:00:00",
  },
  {
    id: "app-4",
    userId: "user-3",
    userName: "Claire Ingabire",
    groupId: "g2",
    groupName: "Kigali Hustlers Fund",
    principal: 40000,
    currency: "RWF",
    interestRate: 3,
    repaymentPeriodDays: 60,
    purpose: "Medical emergency",
    appliedAt: "2025-04-10T08:00:00",
    status: "REJECTED",
    reviewedBy: "Admin Sarah",
    reviewedAt: "2025-04-12T15:00:00",
    rejectionReason: "Insufficient group savings history",
  },
];
