// ─── Dashboard Mock Data ────────────────────────────────────────────────────

export const mockUser = {
  fullName: "Blaise Mucyo",
  email: "blaise@e-kimina.rw",
  image: null,
};

// ─── Stats ──────────────────────────────────────────────────────────────────
export const mockStats = [
  {
    id: "1",
    label: "Groups Joined",
    value: 8,
    change: "+2 this month",
    trend: "up",
    icon: "users",
    accent: "primary",
  },
  {
    id: "2",
    label: "Activities Done",
    value: 34,
    change: "+5 this week",
    trend: "up",
    icon: "zap",
    accent: "accent",
  },
  {
    id: "3",
    label: "Upcoming Events",
    value: 5,
    change: "Next in 2 days",
    trend: "neutral",
    icon: "calendar",
    accent: "primary",
  },
  {
    id: "4",
    label: "Messages",
    value: 12,
    change: "3 unread",
    trend: "up",
    icon: "message",
    accent: "accent",
  },
];

// ─── Recent Activities ───────────────────────────────────────────────────────
export const mockActivities = [
  {
    id: "1",
    type: "join",
    description: "You joined the group",
    target: "Web Dev Rwanda",
    time: "2 hours ago",
    icon: "user-plus",
    color: "primary",
  },
  {
    id: "2",
    type: "event",
    description: "New event scheduled in",
    target: "Design Kigali",
    time: "5 hours ago",
    icon: "calendar",
    color: "accent",
  },
  {
    id: "3",
    type: "message",
    description: "New message from",
    target: "Jean Pierre",
    time: "Yesterday, 4:30 PM",
    icon: "message",
    color: "primary",
  },
  {
    id: "4",
    type: "update",
    description: "Group updated its schedule —",
    target: "AI & ML Africa",
    time: "Yesterday, 11:00 AM",
    icon: "refresh",
    color: "accent",
  },
  {
    id: "5",
    type: "badge",
    description: "You earned a badge in",
    target: "Open Source KGL",
    time: "2 days ago",
    icon: "award",
    color: "primary",
  },
  {
    id: "6",
    type: "leave",
    description: "Session completed in",
    target: "Startup Circle",
    time: "3 days ago",
    icon: "check",
    color: "accent",
  },
];

// ─── Schedule ────────────────────────────────────────────────────────────────
export const mockSchedule = [
  {
    id: "1",
    title: "Web Dev Rwanda — Weekly Sync",
    type: "Meeting",
    time: "09:00 AM",
    duration: "1h",
    day: "Today",
    color: "primary",
  },
  {
    id: "2",
    title: "Design Kigali — UI Workshop",
    type: "Workshop",
    time: "02:00 PM",
    duration: "2h",
    day: "Today",
    color: "accent",
  },
  {
    id: "3",
    title: "AI & ML Africa — Paper Review",
    type: "Session",
    time: "10:00 AM",
    duration: "1h 30m",
    day: "Tomorrow",
    color: "primary",
  },
  {
    id: "4",
    title: "Open Source KGL — Hackathon Prep",
    type: "Planning",
    time: "03:00 PM",
    duration: "2h",
    day: "Tomorrow",
    color: "accent",
  },
  {
    id: "5",
    title: "Startup Circle — Pitch Practice",
    type: "Practice",
    time: "11:00 AM",
    duration: "1h",
    day: "Fri, 18 Apr",
    color: "primary",
  },
];

// ─── Groups ──────────────────────────────────────────────────────────────────
export const mockGroups = [
  {
    id: "1",
    name: "Web Dev Rwanda",
    description: "Full-stack developers community in Rwanda",
    members: 124,
    role: "Member",
    category: "Technology",
    avatar: "WD",
    color: "primary",
    activity: "Active",
    nextEvent: "Today, 9AM",
  },
  {
    id: "2",
    name: "Design Kigali",
    description: "UI/UX designers and creatives in Kigali",
    members: 87,
    role: "Admin",
    category: "Design",
    avatar: "DK",
    color: "accent",
    activity: "Active",
    nextEvent: "Today, 2PM",
  },
  {
    id: "3",
    name: "AI & ML Africa",
    description: "Artificial intelligence research and application",
    members: 213,
    role: "Member",
    category: "Research",
    avatar: "AI",
    color: "primary",
    activity: "Active",
    nextEvent: "Tomorrow",
  },
  {
    id: "4",
    name: "Open Source KGL",
    description: "Contributing to open source from Kigali",
    members: 56,
    role: "Moderator",
    category: "Open Source",
    avatar: "OS",
    color: "accent",
    activity: "Moderate",
    nextEvent: "Fri, 18 Apr",
  },
  {
    id: "5",
    name: "Startup Circle",
    description: "Entrepreneurs and startup founders network",
    members: 98,
    role: "Member",
    category: "Business",
    avatar: "SC",
    color: "primary",
    activity: "Active",
    nextEvent: "Fri, 18 Apr",
  },
  {
    id: "6",
    name: "Data Science RW",
    description: "Data professionals and analytics enthusiasts",
    members: 142,
    role: "Member",
    category: "Data",
    avatar: "DS",
    color: "accent",
    activity: "Moderate",
    nextEvent: "Mon, 21 Apr",
  },
];

// ─── Calendar ────────────────────────────────────────────────────────────────
export const mockCalendarEvents: Record<number, { title: string; color: string }[]> = {
  17: [{ title: "Web Dev Sync", color: "primary" }, { title: "UI Workshop", color: "accent" }],
  18: [{ title: "Pitch Practice", color: "primary" }],
  21: [{ title: "AI Paper Review", color: "accent" }],
  22: [{ title: "Hackathon Prep", color: "primary" }],
  25: [{ title: "Data Science Meet", color: "accent" }],
  28: [{ title: "Startup Meetup", color: "primary" }],
};